name: Modmail Workflow

on: [push, pull_request]

jobs:
  code-style:

#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest, windows-latest, macOS-latest]
#        python-version: [3.6, 3.7]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install bandit pylint black
      continue-on-error: true
    - name: Bandit syntax check
      run: bandit ./bot.py cogs/*.py core/*.py -b .bandit_baseline.json
    - name: Pylint
      run: pylint ./bot.py cogs/*.py core/*.py --disable=import-error  --exit-zero -r y
      continue-on-error: true
    - name: Black and flake8
      run: |
        black . --check
